sudo: required

services:
  - docker

install:
  - docker build -t dockertestimage .

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run -e ci_env -ti dockertestimage /bin/bash -c
      "cd discretisedfield;
      python3 -m pytest --cov=discretisedfield --cov-config .coveragerc;
      python3 -m pytest --nbval docs/ipynb/*.ipynb;
      bash <(curl -s https://codecov.io/bash) -t a96f2545-67ea-442e-a1b6-fdebc595cf52"; echo $?

notifications:
  slack: joommf:eqKxGPXuUP3LxnOfxg7GWgDF