language: python

python:
  - "3.5"

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

install: pip install codecov pytest-cov matplotlib jupyter git+https://github.com/computationalmodelling/nbval.git

script:
#  - py.test --cov=discretisedfield --cov-config .coveragerc
  - make test-code
#  - py.test --nbval docs/ipynb/*.ipynb
  - make test-ipynb

after_success:
  codecov

notifications:
  slack: joommf:eqKxGPXuUP3LxnOfxg7GWgDF
