name: tests

on: [push]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Initialisation
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: python -m pip install --upgrade pip pytest-cov nbval pycodestyle .

    - name: Unit tests
      run: make test-unittests

    - name: Documentation tests
      run: make test-docs

    - name: Jupyter notebook tests
      run: make test-ipynb

    - name: Python code style
      run: make test-pycodestyle

    # Coverage is tested and uploaded only on ubuntu-latest
    - name: Coverage
      run: make test-coverage
      if: matrix.os == 'ubuntu-latest'

    - name: Upload coverage to Codecov.io
      uses: codecov/codecov-action@v1
      if: matrix.os == 'ubuntu-latest'
