name: ci-tests

on: [push]

jobs:
  linux-test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: 'x64'
    - name: Install dependencies
      run: python -m pip install --upgrade pip .
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Display Python version
      run: make test-test
#
#
# name: test
#
# on: [push]
#
# jobs:
#   linux-test:
#     runs-on: ubuntu-20.04
#     strategy:
#       matrix:
#         python-version: [3.8]
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#       - run: npm install -g bats
#       - run: bats -v
