name: tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Initialisation
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: 'x64'
    - name: Install dependencies
      run: python -m pip install --upgrade pip pytest-cov nbval .
    # - name: Run tests
    #   run: make test-test
    - name: Run coverage
      run: make test-coverage
      if: matrix.os == 'ubuntu-latest'
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      if: matrix.os == 'ubuntu-latest'
